// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveOtp = `-- name: FindActiveOtp :one
SELECT id, email, otp, expires_at, created_at FROM email_otps 
WHERE email = $1 
  AND expires_at > NOW() 
ORDER BY created_at DESC 
LIMIT 1
`

func (q *Queries) FindActiveOtp(ctx context.Context, email string) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, findActiveOtp, email)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Otp,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, user_name, email, password, role, source, is_active, is_verified, gender, refresh_token, permissions, created_at, updated_at FROM users 
WHERE email = $1 
LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Source,
		&i.IsActive,
		&i.IsVerified,
		&i.Gender,
		&i.RefreshToken,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, user_name, email, password, role, source, is_active, is_verified, gender, refresh_token, permissions, created_at, updated_at FROM users 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Source,
		&i.IsActive,
		&i.IsVerified,
		&i.Gender,
		&i.RefreshToken,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEmailOtp = `-- name: InsertEmailOtp :one
INSERT INTO email_otps (
    email,
    otp,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, email, otp, expires_at, created_at
`

type InsertEmailOtpParams struct {
	Email     string             `json:"email"`
	Otp       string             `json:"otp"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertEmailOtp(ctx context.Context, arg InsertEmailOtpParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, insertEmailOtp, arg.Email, arg.Otp, arg.ExpiresAt)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Otp,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    user_name,
    email,
    password,
    gender
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_name, email, password, role, source, is_active, is_verified, gender, refresh_token, permissions, created_at, updated_at
`

type InsertUserParams struct {
	UserName pgtype.Text    `json:"user_name"`
	Email    pgtype.Text    `json:"email"`
	Password pgtype.Text    `json:"password"`
	Gender   NullUserGender `json:"gender"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.UserName,
		arg.Email,
		arg.Password,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Source,
		&i.IsActive,
		&i.IsVerified,
		&i.Gender,
		&i.RefreshToken,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserAndUpdateRefreshToken = `-- name: VerifyUserAndUpdateRefreshToken :one
UPDATE users
SET
    refresh_token = $1,
    is_verified = TRUE
WHERE email = $2
RETURNING id
`

type VerifyUserAndUpdateRefreshTokenParams struct {
	RefreshToken pgtype.Text `json:"refresh_token"`
	Email        pgtype.Text `json:"email"`
}

func (q *Queries) VerifyUserAndUpdateRefreshToken(ctx context.Context, arg VerifyUserAndUpdateRefreshTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyUserAndUpdateRefreshToken, arg.RefreshToken, arg.Email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
