// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleCustomer Role = "customer"
	RoleAdmin    Role = "admin"
	RoleVendor   Role = "vendor"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Source string

const (
	SourceGoogle   Source = "google"
	SourceFacebook Source = "facebook"
	SourceWhatsapp Source = "whatsapp"
	SourceGeneral  Source = "general"
)

func (e *Source) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Source(s)
	case string:
		*e = Source(s)
	default:
		return fmt.Errorf("unsupported scan type for Source: %T", src)
	}
	return nil
}

type NullSource struct {
	Source Source `json:"source"`
	Valid  bool   `json:"valid"` // Valid is true if Source is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSource) Scan(value interface{}) error {
	if value == nil {
		ns.Source, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Source.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Source), nil
}

type UserGender string

const (
	UserGenderMale   UserGender = "male"
	UserGenderFemale UserGender = "female"
	UserGenderOther  UserGender = "other"
)

func (e *UserGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserGender(s)
	case string:
		*e = UserGender(s)
	default:
		return fmt.Errorf("unsupported scan type for UserGender: %T", src)
	}
	return nil
}

type NullUserGender struct {
	UserGender UserGender `json:"user_gender"`
	Valid      bool       `json:"valid"` // Valid is true if UserGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserGender) Scan(value interface{}) error {
	if value == nil {
		ns.UserGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserGender), nil
}

type EmailOtp struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Otp       string             `json:"otp"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	UserName     pgtype.Text        `json:"user_name"`
	Email        pgtype.Text        `json:"email"`
	Password     pgtype.Text        `json:"password"`
	Role         Role               `json:"role"`
	Source       Source             `json:"source"`
	IsActive     bool               `json:"is_active"`
	IsVerified   bool               `json:"is_verified"`
	Gender       NullUserGender     `json:"gender"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	Permissions  []string           `json:"permissions"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
