// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindActiveOtp(ctx context.Context, email string) (EmailOtp, error)
	FindUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertEmailOtp(ctx context.Context, arg InsertEmailOtpParams) (EmailOtp, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	VerifyUserAndUpdateRefreshToken(ctx context.Context, arg VerifyUserAndUpdateRefreshTokenParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
