// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceInvitation, error)
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CreateWorkspaceRow, error)
	CreateWorkspaceInvitation(ctx context.Context, arg CreateWorkspaceInvitationParams) (WorkspaceInvitation, error)
	DeleteExpiredInvitations(ctx context.Context) error
	DeleteInvitation(ctx context.Context, id pgtype.UUID) error
	DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) (DeleteWorkspaceRow, error)
	FindActiveOtp(ctx context.Context, email string) (EmailOtp, error)
	FindInvitationByToken(ctx context.Context, token string) (WorkspaceInvitation, error)
	// ~ workspace invitation related queries
	FindMemberByWorkspaceAndEmail(ctx context.Context, arg FindMemberByWorkspaceAndEmailParams) (WorkspaceMember, error)
	FindPendingInvitationByWorkspaceAndEmail(ctx context.Context, arg FindPendingInvitationByWorkspaceAndEmailParams) (WorkspaceInvitation, error)
	FindPendingInvitationsByEmail(ctx context.Context, email string) ([]WorkspaceInvitation, error)
	FindPendingInvitationsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceInvitation, error)
	FindUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	FindUserWorkspacesById(ctx context.Context, arg FindUserWorkspacesByIdParams) (FindUserWorkspacesByIdRow, error)
	FindWorkspacesByUserID(ctx context.Context, createdBy pgtype.UUID) ([]FindWorkspacesByUserIDRow, error)
	InsertEmailOtp(ctx context.Context, arg InsertEmailOtpParams) (EmailOtp, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (pgtype.UUID, error)
	VerifyUserAndUpdateRefreshToken(ctx context.Context, arg VerifyUserAndUpdateRefreshTokenParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
