// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    name,
    created_by,
    image
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    name,
    created_by,
    image,
    created_at,
    updated_at
`

type CreateWorkspaceParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
	Image     pgtype.Text `json:"image"`
}

type CreateWorkspaceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CreateWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.CreatedBy, arg.Image)
	var i CreateWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserWorkspacesById = `-- name: FindUserWorkspacesById :one
SELECT
    id,
    name,
    created_by,
    image,
    created_at,
    updated_at
FROM workspaces
WHERE id = $1 and created_by=$2
`

type FindUserWorkspacesByIdParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type FindUserWorkspacesByIdRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindUserWorkspacesById(ctx context.Context, arg FindUserWorkspacesByIdParams) (FindUserWorkspacesByIdRow, error) {
	row := q.db.QueryRow(ctx, findUserWorkspacesById, arg.ID, arg.CreatedBy)
	var i FindUserWorkspacesByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkspacesByUserID = `-- name: FindWorkspacesByUserID :many
SELECT
    id,
    name,
    created_by,
    image,
    created_at,
    updated_at
FROM workspaces
WHERE created_by = $1
ORDER BY created_at DESC
`

type FindWorkspacesByUserIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindWorkspacesByUserID(ctx context.Context, createdBy pgtype.UUID) ([]FindWorkspacesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findWorkspacesByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindWorkspacesByUserIDRow
	for rows.Next() {
		var i FindWorkspacesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET
    name = $2,
    image = $3,
    updated_at = NOW()
WHERE id = $1 and created_by=$4
RETURNING
    id
`

type UpdateWorkspaceParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Image     pgtype.Text `json:"image"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
