[SERVICE]
    Flush        1
    Log_Level    debug
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

[FILTER]
    Name          parser
    Match         docker.*
    Key_Name      log
    Parser        json
    Reserve_Data  On
    
[OUTPUT]
    Name         loki
    Match        docker.*
    Host         loki
    Port         3100
    Labels       job=fluentbit, app=go-crm
    Line_Format json