package repository

import (
	"context"
	"fmt"
	"time"

	sqlc "github.com/HadeedTariq/dev-trail/internal/adapters/postgresql/sqlc"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

type userRepository struct {
	pool    *pgxpool.Pool
	queries *sqlc.Queries // generated by sqlc
}

func NewUserRepository(pool *pgxpool.Pool, queries *sqlc.Queries) UserRepository {
	return &userRepository{
		pool:    pool,
		queries: queries,
	}
}

func (r *userRepository) GetByEmail(ctx context.Context, email pgtype.Text) (*sqlc.User, error) {
	user, err := r.queries.FindUserByEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *userRepository) GetById(ctx context.Context, id pgtype.UUID) (*sqlc.User, error) {
	user, err := r.queries.FindUserByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

func (r *userRepository) GetActiveOtp(ctx context.Context, email pgtype.Text) (*sqlc.EmailOtp, error) {
	activeOtp, err := r.queries.FindActiveOtp(ctx, email.String)
	if err != nil {
		return nil, err
	}
	return &activeOtp, nil
}

func (r *userRepository) VerifyUserAndUpdateRefreshToken(
	ctx context.Context,
	email pgtype.Text,
	refreshToken pgtype.Text,
) (pgtype.UUID, error) {
	userID, err := r.queries.VerifyUserAndUpdateRefreshToken(ctx, sqlc.VerifyUserAndUpdateRefreshTokenParams{
		RefreshToken: refreshToken,
		Email:        email,
	})
	if err != nil {
		return pgtype.UUID{}, err
	}

	return userID, nil
}

func (r *userRepository) ExecTx(ctx context.Context, fn func(q *sqlc.Queries) error) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin tx: %w", err)
	}

	// ALWAYS defer a rollback.
	// If the transaction is committed successfully later, this deferred call
	// becomes a harmless no-op. If it panics or fails, this guarantees cleanup.
	defer func() {
		_ = tx.Rollback(ctx)
	}()

	// Bind sqlc queries to this active transaction
	qtx := r.queries.WithTx(tx)

	// Execute business function
	if err := fn(qtx); err != nil {
		// Deferred tx.Rollback() will catch this and release the pool connection
		return err
	}

	// Commit transaction
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit tx: %w", err)
	}

	return nil
}

func (r *userRepository) CreateUserWithOTP(ctx context.Context, user *sqlc.User, otp string, expiresAt time.Time) error {
	return r.ExecTx(ctx, func(q *sqlc.Queries) error {
		// 1. Insert User
		_, err := q.InsertUser(ctx, sqlc.InsertUserParams{
			UserName: user.UserName,
			Email:    user.Email,
			Password: user.Password,
			Gender:   user.Gender,
		})
		if err != nil {
			return fmt.Errorf("failed to insert user in tx: %w", err)
		}

		// 2. Insert Email OTP
		_, err = q.InsertEmailOtp(ctx, sqlc.InsertEmailOtpParams{
			Email: user.Email.String,
			Otp:   otp,
			ExpiresAt: pgtype.Timestamptz{
				Time:  expiresAt,
				Valid: true,
			},
		})
		if err != nil {
			return fmt.Errorf("failed to insert email otp in tx: %w", err)
		}

		return nil
	})
}
